/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MailBoxT-v1.glb 
*/

import React, {useEffect, useMemo} from 'react'
import {useAnimations } from '@react-three/drei'
import { useGLTFWithKTX2 } from '../utils/useGLTFWithKTX2'
import { convertMaterialsToMeshBasicMaterial } from '../utils/convertMaterial'
import * as THREE from "three"

export function Model(props) {
    const group = React.useRef()
    const result = useGLTFWithKTX2('/GLBs/Mail//HMT-transformed.glb')
    if(!result) return null;
    const { nodes, materials, animations } = result;
    useMemo(() => {
        convertMaterialsToMeshBasicMaterial(materials);
    }, [materials]);
    const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MailBoxRig" position={[-5.085, 18.002, 6.625]} rotation={[0, -1.489, 0]} scale={0.35}>
          <group name="Lid">
            <mesh name="Latch_Baked" geometry={nodes.Latch_Baked.geometry} material={materials.MailboxParts_Baked} position={[0, 0, 0]} scale={2.854} />
          </group>
          <group name="Flag" position={[0.942, 0.403, 0.737]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh name="Flag_Baked" geometry={nodes.Flag_Baked.geometry} material={materials.MailboxParts_Baked} position={[0, 0, 0]} rotation={[0, 0, Math.PI / 2]} scale={2.854} />
          </group>
          <group name="Bone" position={[0.628, 0.315, -0.376]} rotation={[-0.318, 0.004, -0.026]}>
            <mesh name="Envelope_Baked" geometry={nodes.Envelope_Baked.geometry} material={materials['Envelope_Baked.001']} rotation={[-1.412, 1.545, 1.438]} scale={[0.026, 0.381, 0.522]} />
          </group>
        </group>
        <mesh name="Mailbox_Baked" geometry={nodes.Mailbox_Baked.geometry} material={materials['Mailbox_Baked.001']} position={[-5.061, 16.874, 6.956]} rotation={[0, -1.489, 0]} />
      </group>
    </group>
  )
}
export default React.memo(Model);