/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MobsFinalT.glb --transform -d 
Files: MobsFinalT.glb [1.79MB] > C:\Users\Jovan\OneDrive\Desktop\2025_Portfolio\GLB_Files\NewVersions\MobsFinalT-transformed.glb [1.56MB] (13%)
*/

import React, {useEffect, useMemo} from 'react'
import {useAnimations } from '@react-three/drei'
import { useGLTFWithKTX2 } from '../utils/useGLTFWithKTX2'
import { convertMaterialsToMeshBasicMaterial } from '../utils/convertMaterial'
import * as THREE from "three"

function Model(props) {
  const group = React.useRef()
  const result = useGLTFWithKTX2('/GLBs/Mobs/MobsFinalT-transformed.glb');
  if(!result) return null;

  const { nodes, materials, animations } = result;

  useMemo(() => {
    convertMaterialsToMeshBasicMaterial(materials);
  }, [materials]);

  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if(actions){
      Object.values(actions).forEach((action) => {
        action.play();
      });
    }
  }, [actions]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Pig_Armature" position={[-25.752, 16.413, -15.764]} rotation={[-Math.PI, -0.022, 0]} scale={0.298}>
          <group name="Pig-Torso" position={[0.129, 0, -0.008]} rotation={[0, 0.021, Math.PI / 2]}>
            <group name="Pig-FLL" position={[1.04, 1.195, -0.65]} rotation={[-0.021, 0, -Math.PI / 2]}>
              <mesh name="Pig_FLL_Baked" geometry={nodes.Pig_FLL_Baked.geometry} material={materials.PigLegs2_Baked} position={[-1.022, -0.619, 0.677]} rotation={[Math.PI / 2, 0, -1.592]} scale={0.105} />
            </group>
            <group name="Pig-BLL" position={[1.039, -1.328, -0.65]} rotation={[-0.021, 0, -Math.PI / 2]}>
              <mesh name="Pig_BLL_Baked" geometry={nodes.Pig_BLL_Baked.geometry} material={materials.PigLegs2_Baked} position={[-3.545, -0.619, 0.731]} rotation={[Math.PI / 2, 0, -1.592]} scale={0.105} />
            </group>
            <group name="Pig-BRL" position={[1.039, -1.328, 0.612]} rotation={[-0.021, 0, -Math.PI / 2]}>
              <mesh name="Pig_BRL_Baked" geometry={nodes.Pig_BRL_Baked.geometry} material={materials.PigLegs2_Baked} position={[-3.571, -0.619, -0.53]} rotation={[Math.PI / 2, 0, -1.592]} scale={0.105} />
            </group>
            <group name="Pig-FRL" position={[1.039, 1.196, 0.611]} rotation={[-0.021, 0, -Math.PI / 2]}>
              <mesh name="Pig_FRL_Baked" geometry={nodes.Pig_FRL_Baked.geometry} material={materials.PigLegs2_Baked} position={[-1.049, -0.619, -0.584]} rotation={[Math.PI / 2, 0, -1.592]} scale={0.105} />
            </group>
            <group name="Pig-Head" position={[-0.131, 1.754, 0.004]}>
              <mesh name="Pig_Head_Baked" geometry={nodes.Pig_Head_Baked.geometry} material={materials.Pig_Head_Baked} position={[0.552, 0.477, 0.001]} rotation={[3.142, -1.571, 0]} scale={0.105} />
            </group>
            <mesh name="Pig_Torso_Baked" geometry={nodes.Pig_Torso_Baked.geometry} material={materials['Pig_Torso_Baked.001']} position={[0, 0.129, 0.006]} rotation={[3.142, -1.571, 0]} scale={0.105} />
          </group>
        </group>
        <group name="Pig_Initial_Loc" position={[-25.713, 16.413, -15.762]} scale={0.627} />
        <group name="Villager_Armature" position={[-35.121, 16.413, -15.761]} rotation={[-Math.PI, 0.04, 0]} scale={0.473}>
          <group name="Villager-Torso" position={[43.743, -0.7, -46.78]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Villager-RL" position={[-0.232, 0.005, 0.948]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Villager_RL_Baked" geometry={nodes.Villager_RL_Baked.geometry} material={materials['V-Legs_Set_Baked']} position={[0.232, -0.862, -0.155]} rotation={[Math.PI / 2, 0, 0.046]} scale={0.116} />
            </group>
            <group name="Villager-LL" position={[0.232, 0.005, 0.948]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Villager_LL_Baked" geometry={nodes.Villager_LL_Baked.geometry} material={materials['V-Legs_Set_Baked']} position={[-0.232, -0.862, -0.155]} rotation={[Math.PI / 2, 0, 0.046]} scale={0.116} />
            </group>
            <group name="Villager-Head" position={[0, 0.012, -1.139]}>
              <mesh name="Villager_Head_Baked" geometry={nodes.Villager_Head_Baked.geometry} material={materials['Villager_Head_Baked.001']} position={[0, 0.147, 1.225]} rotation={[Math.PI, 0, 0.046]} scale={0.116} />
            </group>
            <mesh name="Villager_Torso_Baked" geometry={nodes.Villager_Torso_Baked.geometry} material={materials['Villager_Torso_Baked.001']} position={[0.001, 0.121, 0]} rotation={[Math.PI, 0, 0.046]} scale={0.116} />
          </group>
        </group>
        <group name="Villager_Initial_Loc" position={[-15.923, 16.744, 4.78]} />
        <group name="Armature" position={[-17.72, 16.858, 7.571]} rotation={[0, -0.49, Math.PI]} scale={0.461}>
          <group name="Zombie-Villager-Torso" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Zombie-Villager-LL" position={[0.237, 0, 1.211]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Zombie_Villager_LL_Baked" geometry={nodes.Zombie_Villager_LL_Baked.geometry} material={materials['Z-Appendages_Set_Baked']} position={[-0.237, -1.732, 0.002]} rotation={[1.571, 0, 0]} scale={0.119} />
            </group>
            <group name="Zombie-Villager-RL" position={[-0.237, 0, 1.211]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Zombie_Villager_RL_Baked" geometry={nodes.Zombie_Villager_RL_Baked.geometry} material={materials['Z-Appendages_Set_Baked']} position={[0.237, -1.732, 0.002]} rotation={[Math.PI / 2, 0, 0]} scale={0.119} />
            </group>
            <group name="Zombie-Villager-Head" position={[0, 0, -0.522]}>
              <mesh name="Zombie_Villager_Head_Baked" geometry={nodes.Zombie_Villager_Head_Baked.geometry} material={materials.Zombie_Villager_Head_Baked} position={[0, -0.002, 0]} rotation={[Math.PI, 0, 0]} scale={0.119} />
            </group>
            <group name="Zombie-Villager-Arms" position={[0, 0, -0.295]}>
              <mesh name="Zombie_Villager_Arms_Baked" geometry={nodes.Zombie_Villager_Arms_Baked.geometry} material={materials['Z-Appendages_Set_Baked']} position={[0, -0.002, -0.226]} rotation={[Math.PI, 0, 0]} scale={0.119} />
            </group>
            <mesh name="Zombie_Villager_Torso_Baked" geometry={nodes.Zombie_Villager_Torso_Baked.geometry} material={materials.Zombie_Villager_Torso_Baked} position={[0, -0.002, -0.521]} rotation={[Math.PI, 0, 0]} scale={0.119} />
          </group>
        </group>
        <group name="Zombie_Villager_Initial_Loc" position={[-17.72, 16.858, 7.571]} rotation={[0, 1.08, 0]} scale={[0.591, 1.111, 0.449]} />
        <group name="Enderdragon_Armature" position={[73.284, 10.133, 56.291]} rotation={[-Math.PI / 9, 0, -Math.PI]} scale={0.474}>
          <group name="Root" rotation={[2.793, 0, 0]}>
            <group name="Body" position={[0, -0.586, -0.392]} rotation={[-2.062, 0, 0]}>
              <group name="BLU" position={[0, 5.876, 0.138]} rotation={[-0.354, 0, 0]}>
                <group name="BLL" position={[0, 3.75, 0.322]} rotation={[0.256, 0, 0]}>
                  <group name="BLF" position={[0, 4.093, 0.263]} rotation={[-0.414, 0, 0]}>
                    <mesh name="EnderdragonBLF_Baked" geometry={nodes.EnderdragonBLF_Baked.geometry} material={materials.EnderDragonLegs_Baked} position={[0, 1.237, 0.144]} rotation={[0.368, 0, Math.PI]} scale={2.11} />
                  </group>
                  <mesh name="EnderdragonBLL_Baked" geometry={nodes.EnderdragonBLL_Baked.geometry} material={materials.EnderDragonLegs_Baked} position={[0, 1.807, -0.027]} rotation={[-0.268, 0, Math.PI]} scale={2.11} />
                </group>
                <mesh name="EnderdragonBLU_Baked" geometry={nodes.EnderdragonBLU_Baked.geometry} material={materials.EnderDragonLegs_Baked} position={[0, 1.717, 0.083]} rotation={[-0.012, 0, Math.PI]} scale={2.11} />
              </group>
              <group name="S01" position={[0, 7.64, 0.195]} rotation={[0.067, 0, 0]}>
                <group name="S02" position={[0, 1.128, 0]}>
                  <group name="S03" position={[0, 1.281, 0]}>
                    <group name="S04" position={[0, 1.286, 0]}>
                      <group name="S05" position={[0, 1.286, 0]}>
                        <group name="S06" position={[0, 1.278, 0]}>
                          <group name="S07" position={[0, 1.284, 0]}>
                            <group name="S08" position={[0, 1.364, 0]}>
                              <group name="S09" position={[0, 1.375, 0]}>
                                <group name="S10" position={[0, 1.363, 0]}>
                                  <group name="S11" position={[0, 1.365, 0]}>
                                    <group name="S12" position={[0, 1.376, 0.008]}>
                                      <mesh name="Enderdragon_S12_Baked" geometry={nodes.Enderdragon_S12_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.78, 0.446]} rotation={[-0.634, 0, Math.PI]} scale={2.11} />
                                    </group>
                                    <mesh name="Enderdragon_S11_Baked" geometry={nodes.Enderdragon_S11_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.812, 0.438]} rotation={[-0.612, 0, Math.PI]} scale={2.11} />
                                  </group>
                                  <mesh name="Enderdragon_S10_Baked" geometry={nodes.Enderdragon_S10_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.799, 0.459]} rotation={[-0.553, 0, Math.PI]} scale={2.11} />
                                </group>
                                <mesh name="Enderdragon_S9_Baked" geometry={nodes.Enderdragon_S9_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.804, 0.46]} rotation={[-0.528, 0, Math.PI]} scale={2.11} />
                              </group>
                              <mesh name="Enderdragon_S8_Baked" geometry={nodes.Enderdragon_S8_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.814, 0.459]} rotation={[-0.508, 0, Math.PI]} scale={2.11} />
                            </group>
                            <mesh name="Enderdragon_S7_Baked" geometry={nodes.Enderdragon_S7_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.806, 0.464]} rotation={[-0.477, 0, Math.PI]} scale={2.11} />
                          </group>
                          <mesh name="Enderdragon_S6_Baked" geometry={nodes.Enderdragon_S6_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.722, 0.465]} rotation={[-0.451, 0, Math.PI]} scale={2.11} />
                        </group>
                        <mesh name="Enderdragon_S5_Baked" geometry={nodes.Enderdragon_S5_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.718, 0.448]} rotation={[-0.457, 0, Math.PI]} scale={2.11} />
                      </group>
                      <mesh name="Enderdragon_S4_Baked" geometry={nodes.Enderdragon_S4_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.724, 0.439]} rotation={[-0.451, 0, Math.PI]} scale={2.11} />
                    </group>
                    <mesh name="Enderdragon_S3_Baked" geometry={nodes.Enderdragon_S3_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.724, 0.439]} rotation={[-0.429, 0, Math.PI]} scale={2.11} />
                  </group>
                  <mesh name="Enderdragon_S2_Baked" geometry={nodes.Enderdragon_S2_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.719, 0.439]} rotation={[-0.406, 0, Math.PI]} scale={2.11} />
                </group>
                <mesh name="Enderdragon_S1_Baked" geometry={nodes.Enderdragon_S1_Baked.geometry} material={materials.EnderDragonTail_Baked} position={[0, 0.566, 0.439]} rotation={[-0.383, 0, Math.PI]} scale={2.11} />
              </group>
              <group name="RightWing" position={[0.907, 1.007, 0.81]} rotation={[-0.109, 0.541, -1.357]}>
                <group name="RightWingEnd" position={[0.575, 7.402, 0.169]} rotation={[-0.976, -0.001, -0.005]}>
                  <mesh name="Enderdragon_LeftWingEnd_Baked" geometry={nodes.Enderdragon_LeftWingEnd_Baked.geometry} material={materials.EnderDragon_Wings_Baked} position={[-1.813, 3.668, 0.299]} rotation={[0.62, -0.358, -1.764]} scale={2.11} />
                </group>
                <mesh name="Enderdragon_LeftWing_Baked" geometry={nodes.Enderdragon_LeftWing_Baked.geometry} material={materials.EnderDragon_Wings_Baked} position={[-1.278, 4.208, 0.255]} rotation={[-0.058, -0.363, -1.767]} scale={2.11} />
              </group>
              <group name="LeftWing" position={[-0.907, 1.007, 0.81]} rotation={[-0.109, -0.541, 1.357]}>
                <group name="LeftWingEnd" position={[-0.608, 7.316, 0.199]} rotation={[-0.978, 0.002, 0.006]}>
                  <mesh name="Enderdragon_RightWingEnd_Baked" geometry={nodes.Enderdragon_RightWingEnd_Baked.geometry} material={materials.EnderDragon_Wings_Baked} position={[1.793, 3.725, 0.367]} rotation={[0.622, 0.357, 1.765]} scale={2.11} />
                </group>
                <mesh name="Enderdragon_RightWing_Baked" geometry={nodes.Enderdragon_RightWing_Baked.geometry} material={materials.EnderDragon_Wings_Baked} position={[1.278, 4.208, 0.259]} rotation={[-0.057, 0.363, 1.767]} scale={2.11} />
              </group>
              <group name="FLU" position={[0, 0.307, -0.298]} rotation={[-0.216, 0, 0]}>
                <group name="FLB" position={[0, 3.137, 0.346]} rotation={[-0.509, 0, 0]}>
                  <group name="FLF" position={[0, 2.889, 0.624]} rotation={[-0.517, 0, 0]}>
                    <mesh name="Enderdragon_FLF_Baked" geometry={nodes.Enderdragon_FLF_Baked.geometry} material={materials.EnderDragonLegs_Baked} position={[0, 0.875, 0.002]} rotation={[1.097, 0, Math.PI]} scale={2.11} />
                  </group>
                  <mesh name="Enderdragon_FLL_Baked" geometry={nodes.Enderdragon_FLL_Baked.geometry} material={materials.EnderDragonLegs_Baked} position={[0, 1.212, 0.005]} rotation={[0.358, 0, Math.PI]} scale={2.11} />
                </group>
                <mesh name="Enderdragon_FLU_Baked" geometry={nodes.Enderdragon_FLU_Baked.geometry} material={materials.EnderDragonLegs_Baked} position={[0, 1.33, -0.008]} rotation={[-0.151, 0, Math.PI]} scale={2.11} />
              </group>
              <group name="Head" position={[0.066, -6.768, -1.309]} rotation={[-3.071, -Math.PI / 2, 0]}>
                <group name="Jaw" position={[0.765, 2.004, 0]} rotation={[1.571, 1.34, -1.571]}>
                  <mesh name="EnderdragonJaw_Baked" geometry={nodes.EnderdragonJaw_Baked.geometry} material={materials.EnderDragonHead2_Baked} position={[0, 0.884, -0.038]} rotation={[2.613, 0, Math.PI]} scale={2.11} />
                </group>
                <mesh name="EnderdragonHead_Baked" geometry={nodes.EnderdragonHead_Baked.geometry} material={materials.EnderDragonHead2_Baked} position={[-0.543, 2.037, 0]} rotation={[1.571, -1.183, 1.571]} scale={2.11} />
              </group>
              <group name="C5" position={[0, -0.515, -0.218]} rotation={[3.124, -1.57, 0]}>
                <group name="C4" position={[0.258, 1.248, 0]} rotation={[0, 0, -0.011]}>
                  <group name="C3" position={[0.216, 1.247, 0]} rotation={[0, 0, -0.025]}>
                    <group name="C2" position={[0.193, 1.265, 0]} rotation={[0, 0, 0.059]}>
                      <group name="C1" position={[0.277, 1.248, 0]} rotation={[0, 0, -0.023]}>
                        <mesh name="Enderdragon_C1_Baked" geometry={nodes.Enderdragon_C1_Baked.geometry} material={materials.EnderDragonNeck2_Baked} position={[-0.432, 0.552, 0]} rotation={[1.571, -1.222, 1.571]} scale={2.11} />
                      </group>
                      <mesh name="Enderdragon_C2_Baked" geometry={nodes.Enderdragon_C2_Baked.geometry} material={materials.EnderDragonNeck2_Baked} position={[-0.408, 0.559, 0]} rotation={[1.571, -1.244, 1.571]} scale={2.11} />
                    </group>
                    <mesh name="Enderdragon_C3_Baked" geometry={nodes.Enderdragon_C3_Baked.geometry} material={materials.EnderDragonNeck2_Baked} position={[-0.446, 0.541, 0]} rotation={[1.571, -1.185, 1.571]} scale={2.11} />
                  </group>
                  <mesh name="Enderdragon_C4_Baked" geometry={nodes.Enderdragon_C4_Baked.geometry} material={materials.EnderDragonNeck2_Baked} position={[-0.453, 0.55, 0]} rotation={[1.571, -1.211, 1.571]} scale={2.11} />
                </group>
                <mesh name="Enderdragon_C5_Baked" geometry={nodes.Enderdragon_C5_Baked.geometry} material={materials.EnderDragonNeck2_Baked} position={[-0.432, 0.552, 0]} rotation={[1.571, -1.222, 1.571]} scale={2.11} />
              </group>
              <mesh name="Enderdragon_Body_Baked" geometry={nodes.Enderdragon_Body_Baked.geometry} material={materials['Enderdragon_Body_Baked.002']} position={[0, 3.586, 1.644]} rotation={[-0.367, 0, Math.PI]} scale={2.11} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
export default React.memo(Model);

